package installer

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// WriteFstab writes a minimal /etc/fstab to targetRoot using the partition
// devices passed in. We prefer LABEL=… (set by FormatPartitions) over raw
// /dev paths so the target survives kernel device renumberings.
//
// Layout:
//
//	LABEL=ROOT         /         ext4   defaults              0 1
//	LABEL=PEACOCK_ESP  /boot     vfat   defaults,umask=0077   0 2
//
// or for the extlinux/MBR path:
//
//	LABEL=PEACOCK_BOOT /boot     ext2   defaults              0 2
func WriteFstab(ctx context.Context, targetRoot string, parts PartitionPaths) error {
	if targetRoot == "" {
		return fmt.Errorf("installer: WriteFstab: targetRoot required")
	}

	bootLabel, bootFS, bootOpts := fstabBootEntry(ctx, parts.BootDev)

	var sb strings.Builder
	sb.WriteString("# /etc/fstab — generated by peacock-installer\n")
	sb.WriteString("# <device>           <mount>  <fs>   <opts>               <dump> <pass>\n")
	sb.WriteString(fmt.Sprintf("LABEL=ROOT           /        ext4   defaults             0      1\n"))
	if bootLabel != "" {
		sb.WriteString(fmt.Sprintf("LABEL=%-14s /boot    %-6s %-20s 0      2\n",
			bootLabel, bootFS, bootOpts))
	}
	sb.WriteString("tmpfs                /tmp     tmpfs  defaults,nosuid      0      0\n")

	path := filepath.Join(targetRoot, "etc", "fstab")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// fstabBootEntry probes the boot device's actual filesystem via blkid and
// returns (label, fs, mount-opts). On error it returns sane defaults
// matching the v0 grub layout.
func fstabBootEntry(ctx context.Context, dev string) (string, string, string) {
	if dev == "" {
		return "", "", ""
	}
	out, err := exec.CommandContext(ctx, "blkid", "-s", "TYPE", "-o", "value", dev).Output()
	if err != nil {
		return "PEACOCK_ESP", "vfat", "defaults,umask=0077"
	}
	fs := strings.TrimSpace(string(out))
	switch fs {
	case "vfat":
		return "PEACOCK_ESP", "vfat", "defaults,umask=0077"
	case "ext2":
		return "PEACOCK_BOOT", "ext2", "defaults"
	case "ext4":
		return "PEACOCK_BOOT", "ext4", "defaults"
	default:
		return "PEACOCK_BOOT", fs, "defaults"
	}
}

// SetHostname writes hostname to <targetRoot>/etc/hostname and adds a
// 127.0.1.1 line to <targetRoot>/etc/hosts. Idempotent — overwrites
// /etc/hostname, but adds the hosts line only when missing.
func SetHostname(ctx context.Context, targetRoot, hostname string) error {
	if !validHostname(hostname) {
		return fmt.Errorf("installer: SetHostname: %q is not a valid hostname", hostname)
	}
	hostnamePath := filepath.Join(targetRoot, "etc", "hostname")
	if err := os.MkdirAll(filepath.Dir(hostnamePath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(hostnamePath, []byte(hostname+"\n"), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", hostnamePath, err)
	}

	hostsPath := filepath.Join(targetRoot, "etc", "hosts")
	cur, _ := os.ReadFile(hostsPath)
	want := fmt.Sprintf("127.0.1.1\t%s\n", hostname)
	if !strings.Contains(string(cur), want) {
		// Append; if file is missing, create with a sensible default.
		if len(cur) == 0 {
			cur = []byte("127.0.0.1\tlocalhost\n::1\tlocalhost\n")
		}
		cur = append(cur, []byte(want)...)
		if err := os.WriteFile(hostsPath, cur, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", hostsPath, err)
		}
	}
	return nil
}

// SetLocale configures /etc/locale.conf, /etc/vconsole.conf, and
// /etc/localtime symlink inside targetRoot. PUNT: locale.gen handling
// differs across Arch vs Debian:
//
//   - Arch: uncomment the line in /etc/locale.gen, then run locale-gen
//     inside the chroot.
//   - Debian: locales is preconfigured via /etc/default/locale; locale-gen
//     reads /etc/locale.gen the same way after `update-locale` runs.
//
// We do both: uncomment the requested locale line in /etc/locale.gen if
// present, write /etc/locale.conf, then try to run locale-gen in the
// chroot — ignoring failure since the live ISO build is expected to ship
// the locale already generated.
func SetLocale(ctx context.Context, targetRoot, locale, keymap, timezone string) error {
	if targetRoot == "" {
		return fmt.Errorf("installer: SetLocale: targetRoot required")
	}

	// /etc/locale.conf
	if locale != "" {
		path := filepath.Join(targetRoot, "etc", "locale.conf")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		body := fmt.Sprintf("LANG=%s\n", locale)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
		// Best-effort uncomment in locale.gen and regenerate.
		if err := uncommentLocaleGen(targetRoot, locale); err == nil {
			if err := runTagged(ctx, PhaseUserAndConfig,
				"chroot", targetRoot, "locale-gen"); err != nil {
				logf(PhaseUserAndConfig, "locale-gen failed: %v (continuing)", err)
			}
		}
	}

	// /etc/vconsole.conf for the console keymap.
	if keymap != "" {
		path := filepath.Join(targetRoot, "etc", "vconsole.conf")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		body := fmt.Sprintf("KEYMAP=%s\n", keymap)
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	// /etc/localtime — symlink to the zoneinfo file.
	if timezone != "" {
		zonePath := filepath.Join("/usr/share/zoneinfo", timezone)
		// Verify the zone exists inside the target before symlinking.
		if _, err := os.Stat(filepath.Join(targetRoot, zonePath)); err != nil {
			return fmt.Errorf("installer: timezone %q not found in target zoneinfo", timezone)
		}
		localtime := filepath.Join(targetRoot, "etc", "localtime")
		_ = os.Remove(localtime)
		if err := os.Symlink(zonePath, localtime); err != nil {
			return fmt.Errorf("symlink %s → %s: %w", localtime, zonePath, err)
		}
	}
	return nil
}

// uncommentLocaleGen finds the requested locale line in
// <targetRoot>/etc/locale.gen, strips the leading "# " if present, and
// rewrites the file. Returns nil quietly when the file doesn't exist
// (some distros don't ship one) so SetLocale can decide whether to call
// locale-gen.
func uncommentLocaleGen(targetRoot, locale string) error {
	path := filepath.Join(targetRoot, "etc", "locale.gen")
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	lines := strings.Split(string(data), "\n")
	changed := false
	// Match "en_US.UTF-8" against "#en_US.UTF-8 UTF-8" or "# en_US.UTF-8 UTF-8".
	for i, ln := range lines {
		trim := strings.TrimLeft(ln, "# \t")
		if strings.HasPrefix(trim, locale+" ") || trim == locale {
			lines[i] = trim
			changed = true
		}
	}
	if !changed {
		return nil
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
}
